pipeline {
    agent any

    stages {
        stage('build') {
            steps {
                sh 'g++ main.cpp -o simple-db'
                archiveArtifacts artifacts: 'simple-db', fingerprint: true
            }
        }
    }
}