pipeline {
    agent any

    stages {
        stage('build') {
            steps {
                sh 'g++ main.cpp -o simple-db'
            }
        }
        stage('test') {
            steps {
				sh 'PATH=$PATH:$PWD'
				sh 'python3 -m venv venv'
				sh '. venv/bin/activate'
				sh 'pip3 install -r tests/requirements.txt'
				sh 'pytest -v tests/test_simple_db.py'
            }
        }
    }
}